# This is a basic workflow to help you get started with Actions

name: build-deploy
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # generate Docker tags based on the following events/attributes
          images: ${{ github.repository }}
            
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - 
        name: Git checkout
        uses: actions/checkout@v2
      -
        name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
        uses: docker/build-push-action@v2.9.0
        with:
          tags: ${{ github.repository }}:${{ github.sha }}
          # List of metadata for an image
          labels: ${{ steps.meta.outputs.labels }}
          push: true
      - name: Checkout Stanton-I Configuration Repo
        uses: actions/checkout@v2.5.0
        with:
          # Repository name with owner. For example, actions/checkout
          repository: biclighter81/stanton-i
          ref: main
          token: ${{ secrets.PAT }}
      - name: Apply new Image Tag
        uses: mikefarah/yq@v4.30.5
        with:
          cmd: yq -i '.spec.template.spec.containers.0.image = "${{ github.repository }}:${{ github.sha }}"' 'deployments/${{ github.event.repository.name }}/01-${{ github.event.repository.name }}-deployment.yaml'
      - name: Commit and push changes to Stanton-I Configuration Repo
        run: |
          git config --global user.name "CI"
          git config --global user.email "ci@rimraf.de"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Updating image tag of repo ${{ github.repository }} to ${{ github.sha }}"
          git push   